package chord;

import javax.swing.DefaultListModel;

public class NoteList {
    public static double frequencyInterval = 3.9; //Hz
    
    private DefaultListModel<Note> noteList;
            
    public NoteList() {
        noteList = new DefaultListModel<>();
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//0 		0,0 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//1 		3,9 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//2 		7,8 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//3 		11,7 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//4 		15,6 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//5 		19,5 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//6 		23,4 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.SUB_CONTRA)); 	//7 		27,3 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//8 		31,2 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//9 		35,1 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//10 		39,0 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//11 		42,9 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//12 		46,8 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//13 		50,7 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//14 		54,6 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.CONTRA)); 	//15 		58,5 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//16 		62,4 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//17 		66,3 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//18 		70,2 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//19 		74,1 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//20 		78,0 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//21 		81,9 Hz
        noteList.addElement(new Note(Note.Pitch.PREVIOUS_CHORD_NOTE, Note.Octave.GREAT)); 	//22 		85,8 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//23 		89,7 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//24 		93,6 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//25 		97,5 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//26 		101,4 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//27 		105,3 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//28 		109,2 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//29 		113,1 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//30 		117,0 Hz
        noteList.addElement(new Note(Note.Pitch.NEXT_CHORD_NOTE, Note.Octave.GREAT)); 	//31 		120,9 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.SMALL)); 	//32 		124,8 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.SMALL)); 	//33 		128,7 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.SMALL)); 	//34 		132,6 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.SMALL)); 	//35 		136,5 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.SMALL)); 	//36 		140,4 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.SMALL)); 	//37 		144,3 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.SMALL)); 	//38 		148,2 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.SMALL)); 	//39 		152,1 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.SMALL)); 	//40 		156,0 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.SMALL)); 	//41 		159,9 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.SMALL)); 	//42 		163,8 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.SMALL)); 	//43 		167,7 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.SMALL)); 	//44 		171,6 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.SMALL)); 	//45 		175,5 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.SMALL)); 	//46 		179,4 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.SMALL)); 	//47 		183,3 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.SMALL)); 	//48 		187,2 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.SMALL)); 	//49 		191,1 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.SMALL)); 	//50 		195,0 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.SMALL)); 	//51 		198,9 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.SMALL)); 	//52 		202,8 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.SMALL)); 	//53 		206,7 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.SMALL)); 	//54 		210,6 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.SMALL)); 	//55 		214,5 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.SMALL)); 	//56 		218,4 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.SMALL)); 	//57 		222,3 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.SMALL)); 	//58 		226,2 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.SMALL)); 	//59 		230,1 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.SMALL)); 	//60 		234,0 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.SMALL)); 	//61 		237,9 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.SMALL)); 	//62 		241,8 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.SMALL)); 	//63 		245,7 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.SMALL)); 	//64 		249,6 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.ONE_LINE)); 	//65 		253,5 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.ONE_LINE)); 	//66 		257,4 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.ONE_LINE)); 	//67 		261,3 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.ONE_LINE)); 	//68 		265,2 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.ONE_LINE)); 	//69 		269,1 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.ONE_LINE)); 	//70 		273,0 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.ONE_LINE)); 	//71 		276,9 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.ONE_LINE)); 	//72 		280,8 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.ONE_LINE)); 	//73 		284,7 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.ONE_LINE)); 	//74 		288,6 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.ONE_LINE)); 	//75 		292,5 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.ONE_LINE)); 	//76 		296,4 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.ONE_LINE)); 	//77 		300,3 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.ONE_LINE)); 	//78 		304,2 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.ONE_LINE)); 	//79 		308,1 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.ONE_LINE)); 	//80 		312,0 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.ONE_LINE)); 	//81 		315,9 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.ONE_LINE)); 	//82 		319,8 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.ONE_LINE)); 	//83 		323,7 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.ONE_LINE)); 	//84 		327,6 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.ONE_LINE)); 	//85 		331,5 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.ONE_LINE)); 	//86 		335,4 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.ONE_LINE)); 	//87 		339,3 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.ONE_LINE)); 	//88 		343,2 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.ONE_LINE)); 	//89 		347,1 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.ONE_LINE)); 	//90 		351,0 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.ONE_LINE)); 	//91 		354,9 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.ONE_LINE)); 	//92 		358,8 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.ONE_LINE)); 	//93 		362,7 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.ONE_LINE)); 	//94 		366,6 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.ONE_LINE)); 	//95 		370,5 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.ONE_LINE)); 	//96 		374,4 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//97 		378,3 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//98 		382,2 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//99 		386,1 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//100 		390,0 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//101 		393,9 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.ONE_LINE)); 	//102 		397,8 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//103 		401,7 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//104 		405,6 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//105 		409,5 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//106 		413,4 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//107 		417,3 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.ONE_LINE)); 	//108 		421,2 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//109 		425,1 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//110 		429,0 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//111 		432,9 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//112 		436,8 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//113 		440,7 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//114 		444,6 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.ONE_LINE)); 	//115 		448,5 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//116 		452,4 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//117 		456,3 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//118 		460,2 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//119 		464,1 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//120 		468,0 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//121 		471,9 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.ONE_LINE)); 	//122 		475,8 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//123 		479,7 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//124 		483,6 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//125 		487,5 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//126 		491,4 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//127 		495,3 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//128 		499,2 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.ONE_LINE)); 	//129 		503,1 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//130 		507,0 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//131 		510,9 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//132 		514,8 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//133 		518,7 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//134 		522,6 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//135 		526,5 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//136 		530,4 Hz
        noteList.addElement(new Note(Note.Pitch.C, Note.Octave.TWO_LINE)); 	//137 		534,3 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//138 		538,2 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//139 		542,1 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//140 		546,0 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//141 		549,9 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//142 		553,8 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//143 		557,7 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//144 		561,6 Hz
        noteList.addElement(new Note(Note.Pitch.CIS, Note.Octave.TWO_LINE)); 	//145 		565,5 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//146 		569,4 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//147 		573,3 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//148 		577,2 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//149 		581,1 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//150 		585,0 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//151 		588,9 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//152 		592,8 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//153 		596,7 Hz
        noteList.addElement(new Note(Note.Pitch.D, Note.Octave.TWO_LINE)); 	//154 		600,6 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//155 		604,5 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//156 		608,4 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//157 		612,3 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//158 		616,2 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//159 		620,1 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//160 		624,0 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//161 		627,9 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//162 		631,8 Hz
        noteList.addElement(new Note(Note.Pitch.DIS, Note.Octave.TWO_LINE)); 	//163 		635,7 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//164 		639,6 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//165 		643,5 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//166 		647,4 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//167 		651,3 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//168 		655,2 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//169 		659,1 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//170 		663,0 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//171 		666,9 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//172 		670,8 Hz
        noteList.addElement(new Note(Note.Pitch.E, Note.Octave.TWO_LINE)); 	//173 		674,7 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//174 		678,6 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//175 		682,5 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//176 		686,4 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//177 		690,3 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//178 		694,2 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//179 		698,1 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//180 		702,0 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//181 		705,9 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//182 		709,8 Hz
        noteList.addElement(new Note(Note.Pitch.F, Note.Octave.TWO_LINE)); 	//183 		713,7 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//184 		717,6 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//185 		721,5 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//186 		725,4 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//187 		729,3 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//188 		733,2 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//189 		737,1 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//190 		741,0 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//191 		744,9 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//192 		748,8 Hz
        noteList.addElement(new Note(Note.Pitch.FIS, Note.Octave.TWO_LINE)); 	//193 		752,7 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//194 		756,6 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//195 		760,5 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//196 		764,4 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//197 		768,3 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//198 		772,2 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//199 		776,1 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//200 		780,0 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//201 		783,9 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//202 		787,8 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//203 		791,7 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//204 		795,6 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//205 		799,5 Hz
        noteList.addElement(new Note(Note.Pitch.G, Note.Octave.TWO_LINE)); 	//206 		803,4 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//207 		807,3 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//208 		811,2 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//209 		815,1 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//210 		819,0 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//211 		822,9 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//212 		826,8 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//213 		830,7 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//214 		834,6 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//215 		838,5 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//216 		842,4 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//217 		846,3 Hz
        noteList.addElement(new Note(Note.Pitch.GIS, Note.Octave.TWO_LINE)); 	//218 		850,2 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//219 		854,1 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//220 		858,0 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//221 		861,9 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//222 		865,8 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//223 		869,7 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//224 		873,6 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//225 		877,5 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//226 		881,4 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//227 		885,3 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//228 		889,2 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//229 		893,1 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//230 		897,0 Hz
        noteList.addElement(new Note(Note.Pitch.A, Note.Octave.TWO_LINE)); 	//231 		900,9 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//232 		904,8 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//233 		908,7 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//234 		912,6 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//235 		916,5 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//236 		920,4 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//237 		924,3 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//238 		928,2 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//239 		932,1 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//240 		936,0 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//241 		939,9 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//242 		943,8 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//243 		947,7 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//244 		951,6 Hz
        noteList.addElement(new Note(Note.Pitch.AIS, Note.Octave.TWO_LINE)); 	//245 		955,5 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//246 		959,4 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//247 		963,3 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//248 		967,2 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//249 		971,1 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//250 		975,0 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//251 		978,9 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//252 		982,8 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//253 		986,7 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//254 		990,6 Hz
        noteList.addElement(new Note(Note.Pitch.H, Note.Octave.TWO_LINE)); 	//255 		994,5 Hz
    }
    
    public int getNumberOfNotes() {
        return noteList.getSize();
    }
    
    public Note getNote(int i) {
        return noteList.get(i);
    }
}
